### ISSUE TITLE
wf_set_key gives pop up message 'Keyring password'

### ISSUE THREAD

**Issue by sofialafuente** [bluegreen-labs/ecmwfr#113]
Hi I am having issues downloading data into a HPC. I do the following:

wf_set_key(user = "12345",
            key = key,
            service = "cds")
It works perfect when I download to my local machine, but when I try to run this in the HPC I get the following:

Your keyring is locked please unlock with your keyring password!
Keyring password:

I enter what I think is mykey but it gives me the following error:

Error: yml must be a named list of length 3 with entries ‘c’, ‘keyring_info’, ‘items’ 

I tried entering: 

user, key, cds and many other things but the problem keeps happening. Any help would be appreciated.

**Comment by khufkens** [comment]
Use file based keychain management, as described here:

https://github.com/bluegreen-labs/ecmwfr#file-based-keychains

**Comment by sofialafuente** [comment]
That worked, thank you so much!

**Comment by khufkens** [comment]
Sorry about the slow replies, busy days. Happy hacking

**Comment by khufkens** [comment]
The procedure is as follows:

To install the key:
```r
# on a linux system call before each script (or put it in the startup setting of your R session)
# this will state that the key should be stored and retrieved from file
options(keyring_backend="file") 

# set your key after enabling this option
wf_set_key(user = "1234",
            key = "abcd1234-foo-bar-98765431-XXXXXXXXXX",
            service = "cds"
)
```

To run a script:
```r
# on a linux system call before each script (or put it in the startup setting of your R session)
# this will state that the key should be stored and retrieved from file
options(keyring_backend="file") 

request <- list(
    code = code,
    kwargs = list(
      var = "Near-Surface Air Temperature",
      lat = 50,
      lon = 20
    ),
    workflow_name = "plot_time_series",
    target = "test.nc"
  )

  # Execute the script via the API
  # as you would for a data request
  wf_request(
      request,
      user = "1234"
    )
```

**Comment by khufkens** [comment]
A runner is a virtual machine which does not retain it state (well there are ways to buffer, but I won't go into this).

What you do is you setup an environmental variable with your API key (you should never put it in a repo in plain text, as this is bad practice).

You set the key as per usual, at the start of every runner session. Validate if it works.

You can then run the remaining script.

Be careful what you set up, runners cost money and you don't want to leverage this too much (claiming "free" resources and then spoiling the game for others). Github has slowly starting to decrease the capacity on the free tier due to in part the runner (free compute) time.

Long short, I would not run jobs on github. I do small queries for code coverage but that's about the scope you should expect.

**Comment by khufkens** [comment]
Add this (see test routines package):

```r
# set options
options(keyring_backend="file")

# spoof keyring
if(!("ecmwfr" %in% keyring::keyring_list()$keyring)){
  keyring::keyring_create("ecmwfr", password = "test")
}
```

**Comment by zackarno** [comment]
That seems to have worked - amazing!

Do you have a link for "test routines package" - i'm not sure what you are referring to.

 Thanks a million!!
