### ISSUE TITLE
Increase unit tests / code coverage

### ISSUE THREAD

**Issue by khufkens** [bluegreen-labs/ecmwfr#98]
R6 implementation shifted things about needs more unit tests to cover functions.

- `wf_transfer()`
- ...

**Comment by eliocamp** [comment]
`wf_transfer()` needs to be better adapted to the new implementation, I think. Ideally, it could only be `url$transfer()` since all the work is donde in the class. However, right now it has a lot of code to cover the case of `url` being a.. you know, an URL 🤣. Is this needed? 

If it is, then I think it should change a bit. Instead of doing all that work, it should just create a new request object with the hardcoded URL (no `request$submit()` needed) and then call `request$transfer()`.

**Comment by khufkens** [comment]
Bumped things up (69%), but gui related calls and error trapping which can't be triggered (e.g. servers offline etc) pull coverage down. Most important parts are now tested though.

**Comment by khufkens** [comment]
FYI. Think things are now set for release 1.4!
