### ISSUE TITLE
Confused by the new update of `wf_transfer()`

### ISSUE THREAD

**Issue by Rafnuss** [bluegreen-labs/ecmwfr#99]
Hey! Thanks a lot for this package. Really cool
I'm a bit confuse with the new changes 
I used to download my requests with
```
r <- wf_transfer(url = req[[i_s]]$request_id, service = "cds", user = cds.user, path = dir.save, filename = filename)
```
but now I need to use:
```
wf_transfer(url = basename(req[[i_s]]$get_url()), service = "cds", user = cds.user, path = dir.save, filename = filename)
```

In both case, it seems that I need to provide a `request_id` (e.g., a4120861-ba94-4ced-b9a0-17b06fb1266a) and not an url. 
In both case, that seems to be different from the example provided https://bluegreen-labs.github.io/ecmwfr/reference/wf_transfer.html#examples. Is it because it's a CDS service?

**Comment by eliocamp** [comment]
This is a byproduct of the new internals. I think that you can just do `req$transfer()` and it should work (no need to add all the other information like service, user, usw.. since that should be information already on the request. 

I never used the `wf_transfer()` workflow so, what should we do here, @khufkens ? It could be easy to add a `request_id` slot to the request object for compatibility with the previous code.

**Comment by khufkens** [comment]
Ah, the above didn't answer your question @eliocamp. Yes, adding the request_id would solve this.

**Comment by khufkens** [comment]
Thanks for the fix. I vaguely remember that we discussed this before but seemingly it didn't make it into the submission to CRAN. Anyway, the aging brain. Will merge the pull tomorrow. Getting late here.

**Comment by martindoublem** [comment]
Hi there, landed on the same issue today. Was about to open an 

Another way around this would be to remove the service cds from this  line (not sure for ADS):
https://github.com/bluegreen-labs/ecmwfr/blob/85d0b5636ba70cb07ca3e2c3164f07155a39ae5a/R/wf_transfer.R#L65

in order to keep using the url given by the get_url() function.

But I honestly think the best fix would be to have options for both url and id to wf_transfer function as arguments.

**Comment by khufkens** [comment]
Good catch, actually it is one above that needs to be changed, but same idea:

https://github.com/bluegreen-labs/ecmwfr/blob/85d0b5636ba70cb07ca3e2c3164f07155a39ae5a/R/wf_transfer.R#L55

Will look into it. Feel free to do a pull request as well.

**Comment by martindoublem** [comment]
Yes that is the one I meant.

I actually just checked the file transfer ed by wf_transfer and it seems like it is not the right file that was downloaded. I will double check all this when I have this when I have time to do PR when I have time and I can proceed to do so (I am supposed to be focused on my own work at the moment).

Thanks. Maybe this issue could be reopened in the meantime or should I open a different issue with my suggestions on how to fix this?

**Comment by martindoublem** [comment]
the new request.transfer() seems good though!

**Comment by khufkens** [comment]
I'll reopen, but this technically not a priority. This is around for backward compatibility so people could update old code more easily by swapping out the url string for `basename(req[[i_s]]$get_url())` without reconsidering their whole code base.

**Comment by khufkens** [comment]
But yes, having it work truly out of the box should be preferred. Any contributions are welcome, but check back before you start as I might have closed it if I find some time later.
